# .streamlit/secrets.toml

MAIL_PASSWORD = "qjed acsf ezcl tlxw"

# --- Google Sheets ---
GOOGLE_SERVICE_ACCOUNT_JSON = """
{
  "type": "service_account",
  "project_id": "yorgios-app-6a715",
  "private_key_id": "e74c29ecbcc3f8eb97162bb1f21c1f6154e90a06",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSjAgEAAoIBAQCzkPQYpYVLdmKi\n...VOT1Adtef4bENQDlf4AMKpeCBatrStt/oqBnJcQQdpCbxAoGBAM4bFHs6esnOK\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-service-account@yorgios-app-6a715.iam.gserviceaccount.com",
  "client_id": "111500074709716387757",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service-account%40yorgios-app-6a715.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

# --- Firebase Cloud Messaging ---
FIREBASE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n... votre clé ...\n-----END PRIVATE KEY-----\n",
  "client_email": "...",
  ...
}
"""

# (optionnel) tokens pour push FCM
FCM_TOKEN_CUISINE = "VOTRE_TOKEN_FCM_CUISINE"
FCM_TOKEN_PATRON  = "VOTRE_TOKEN_FCM_PATRON"
