MAIL_PASSWORD = "qjed acsf ezcl tlxw"

GOOGLE_SERVICE_ACCOUNT_JSON = '''
{
  "type": "service_account",
  "project_id": "app-yorgios",
  "private_key_id": "81a2ced33c68cd04380565ff0dea70ebefe00ef8",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9PifMeYDjb/Wi\\nLJZ0zSnAiYQZ4/0bH9z9L5syCSVMXQMJf/wDeoLeal+1Bt43aO1NO8x4Kto1GNk+\\nUgVUW1+NfM11IJ4g3224BElpFeL8q9QxhfvbXR5ZAqBSFfNg4Hqf3SviplNO9jjX\\n6e7rT/ywMVoZpMuv0mr3vq0SBWZKyE9AQMgHZSDsb04fvmaoZfOroqHikO/0CGIT\\nrq4DxBy8TAa/NSXFsU/FEL2rqwm/jJRKHeDolQBa5caWLn1XfMMm/wYnF3Wtlqoj\\nFd5g1YkeKnD52uU9OVgGkQmhVURciYrTjaPK1wnn51CN+hi8qxli8gRX4teSs64J\\n6+IAzCJJAgMBAAECggEAFTXtvQfTT+qhE+u+c1n5d4iSQ1qf6FXibYhT80A...
  "client_email": "streamlit-service@app-yorgios.iam.gserviceaccount.com",
  "client_id": "108063064562304805186",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service%40app-yorgios.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''
